apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prod-slf-k8-baseproject-secret
  namespace: prod-slf-k8-baseproject-ns
spec:
  encryptedData:
    OKTA_CONSUMER_CLIENT_SECRET: AgBKB4CvTqbzQeVHbs/CUXTaqrKM2Tc1U84/P4LlNN8DzkmF+OdeD1kNj991PSyNYgd+MN4DrzXDzbCRWpSXoAJ+uBtLRqOjJibLpJDThEY4mS9/dQBu//b/iA0ocSmLQ6+5huy/3MEm4xYNtjhvRz2LZcll/ovcQWIWppRwPSBOEx+aTekl7FbDPBcFeYpC690vEJenUTXALJkNKfNRDD3HkIYVC6A+bas8CijH59yAQ4onYaO0mUDAfxY0i79zfVw7c0Zembwo3TIrPVppK1vwhSN0B1IjrduN0tYgWdN1jQLkeZ/JLGtI5kereFQf9n87930CqUK88aNBrw4g4Mkwj6nT3f1ccRDxbf1yw+YHgw99XkyjPGRA6nhj8p86JhFIrTlWEfm5YCOx34ipzqIXW07E8IIJuDH3R2MMnfMwyCMYFsBqfZ9FxEjKRP9iEbEXNFAmacqMzBBb8PrGXUdsjxnszLijf1xXqKoU/MM57W1xLEry7urN5vuoi3wmlv9VsPa5R5hbqSWcpLLV/v5SP4MO9uF2O/wCNXuMYfKxRORBfstll3ck9Mj4fBg31KaBPHBWKfm5vPtJeCakEgDnYB87LsNYHyNhSk0dfDxAs8QfUKyDyyMEJCk+073ljFkoAq8RtIlCe9C7YTvvd4DysjxBuQuLUbRbil20i50i7kSx5Mc/M1oEAr6onOslUqPJEBoJh96ZvJ6Ow2O63UFvEqDjW7qLscW7FER25BYZPcGpSWhxszPh
  template:
    metadata:
      creationTimestamp: null
      name: prod-slf-k8-baseproject-secret
      namespace: prod-slf-k8-baseproject-ns
    type: Opaque

