---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
  selfLink: /java-template/namespaces/default/secrets/regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgCSJzdjUxNjA3MC5waC5zdW5saWZlOjgwODEiOiB7CiAgICAgICAgCSJhdXRoIjogIlpuQm9ZWEowYVdaaFkzUnZjbms2WnlSelZVNUFjRkpoS21FeWNqSkRjZz09IgogICAgICAgIH0KCX0sCiAgICAiSHR0cEhlYWRlcnMiOiB7CiAgICAJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy4xNCAobGludXgpIgoJfQp9Cg==